service: auth-service
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerImage: public.ecr.aws/sam/build-python3.12
    dockerizePip: 'non-linux'
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64']
    layer: true
    slim: false
functions:
  app:
    environment:
      DEBUG: ${env:DEBUG}
      STAGE: ${env:STAGE}
      APP_NAME: ${env:APP_NAME}
      APP_TIMEZONE: ${env:APP_TIMEZONE}
      CACHE_SERVICE_BASE_URL: ${env:CACHE_SERVICE_BASE_URL}
      JWT_SECRET: ${env:JWT_SECRET}
      JWT_TOKEN_LIFETIME: ${env:JWT_TOKEN_LIFETIME}
      LOG_LEVEL: DEBUG
      POWERTOOLS_LOGGER_LOG_EVENT: true
      POWERTOOLS_METRICS_NAMESPACE: auth
      POWERTOOLS_SERVICE_NAME: auth-service
    events:
      - httpApi: '*'
    handler: app.main.handler
    layers:
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:73
      - Ref: PythonRequirementsLambdaLayer
package:
  patterns:
    - '!.DS_Store'
    - '!.coverage'
    - '!.env'
    - '!.git/**'
    - '!.idea/**'
    - '!.pytest_cache/**'
    - '!.serverless/**'
    - '!.serverless_plugins/**'
    - '!.terraform/**'
    - '!.terraform.lock.hcl'
    - '!.venv/**'
    - '!coverage.xml'
    - '!htmlcov/**'
    - '!node_modules/**'
provider:
  name: aws
  architecture: x86_64
  memorySize: 512
  region: ${env:AWS_REGION, 'eu-central-1'}
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt usersTable.Arn
            - !Sub ${usersTable.Arn}/index/EmailIndex
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
useDotenv: true
