service: auth-service
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerImage: public.ecr.aws/sam/build-python3.12
    dockerizePip: 'non-linux'
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64']
    layer: true
    zip: true
functions:
  app:
    environment:
      DEBUG: ${env:DEBUG}
      STAGE: ${env:STAGE}
      APP_NAME: ${env:APP_NAME}
      APP_TIMEZONE: ${env:APP_TIMEZONE}
      CACHE_SERVICE_BASE_URL: ${env:CACHE_SERVICE_BASE_URL}
      JWT_SECRET: ${env:JWT_SECRET}
      JWT_TOKEN_LIFETIME: ${env:JWT_TOKEN_LIFETIME}
      LOG_LEVEL: DEBUG
      POWERTOOLS_LOGGER_LOG_EVENT: true
      POWERTOOLS_METRICS_NAMESPACE: auth
      POWERTOOLS_SERVICE_NAME: auth-service
    events:
      - httpApi: '*'
    handler: app.main.handler
    layers:
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:20
      - Ref: PythonRequirementsLambdaLayer
provider:
  name: aws
  memorySize: 512
  region: eu-central-1
  runtime: python3.12
  stage: dev
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: ${env:AWS_ARN_DYNAMODB}
useDotenv: true
