service: auth-service
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerImage: public.ecr.aws/shogo82148/lambda-python:3.10
    dockerizePip: false
    layer: true
    slim: true
    strip: false
    zip: true
functions:
  app:
    environment:
      APP_NAME: ${env:APP_NAME}
      APP_STAGE: ${env:APP_STAGE}
      APP_TIMEZONE: ${env:APP_TIMEZONE}
      CACHE_SERVICE_BASE_URL: ${env:CACHE_SERVICE_BASE_URL}
      DEBUG: ${env:DEBUG}
      JWT_SECRET: ${env:JWT_SECRET}
      JWT_TOKEN_LIFETIME: ${env:JWT_TOKEN_LIFETIME}
      LOG_LEVEL: DEBUG
      POWERTOOLS_LOGGER_LOG_EVENT: true
      POWERTOOLS_METRICS_NAMESPACE: auth
      POWERTOOLS_SERVICE_NAME: auth-service
    events:
      - httpApi: '*'
    handler: app.main.handler
    layers:
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:20
      - Ref: PythonRequirementsLambdaLayer
package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.DS_Store'
    - '!npm-debug.log'
    - '!.serverless/**'
    - '!.serverless_plugins/**'
    - '!.venv/**'
  excludeDevDependencies: true
provider:
  name: aws
  region: eu-central-1
  runtime: python3.10
  stage: dev
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: ${env:AWS_ARN_DYNAMODB}
useDotenv: true
